language: generic 
sudo: required
services: 
    - docker

before_install:
    - docker build -t danjsiegel/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true danjsiegel/docker-react npm run test